from mingus.containers import Track,Bar,Note
snaretrack = Track()
basetrack = Track()
highhattrack = Track()
tomtrack = Track()
cymbaltrack = Track()
snare = Note()
snare.from_int(26)
highhat = Note()
highhat.from_int(30)
openhighhat = Note()
openhighhat.from_int(34)
base = Note()
base.from_int(23)
hightom = Note()
hightom.from_int(38)
midtom = Note()
midtom.from_int(36)
lowtom = Note()
lowtom.from_int(35)
cymbal = Note()
cymbal.from_int(37)
rimshot = Note()
rimshot.from_int(25)
electricsnare = Note()
electricsnare.from_int(28)
ridecymbal = Note()
ridecymbal.from_int(47)
crashcymbal = Note()
crashcymbal.from_int(45)
def dopercussion(snaret,baset,highhatt,tomt,cymbalt):
    highhatt.add_notes(None,4)
    for i in range(0,64):
        highhatt.add_notes(highhat,0.5)
    for i in range(0,28):
        highhatt.add_notes(openhighhat,1)
    highhatt.add_notes(openhighhat,0.75)
    highhatt.add_notes(None,0.75)
    highhatt.add_notes(openhighhat,0.75)
    highhatt.add_notes(None,0.75)
    highhatt.add_notes(openhighhat,1)
    highhatt.add_notes(None,4)

    baset.add_notes(None,4)
    for i in range(0,3):
        baset.add_notes(base,0.75)
        baset.add_notes(None,0.75)
        baset.add_notes(base,0.75)
        baset.add_notes(None,0.25)
        baset.add_notes(base,0.5)
        baset.add_notes(None,0.5)
        baset.add_notes(base,0.5)
        baset.add_notes(base,0.75)
        baset.add_notes(None,0.75)
        baset.add_notes(base,0.75)
        baset.add_notes(None,0.25)
        baset.add_notes(base,0.5)
        baset.add_notes(None,1)
    baset.add_notes(base, 0.75)
    baset.add_notes(None, 0.75)
    baset.add_notes(base, 0.75)
    baset.add_notes(None, 0.25)
    baset.add_notes(base, 0.5)
    baset.add_notes(None, 0.5)
    baset.add_notes(base, 0.5)
    baset.add_notes(base,1)
    baset.add_notes(base,1)
    baset.add_notes(base,1)
    baset.add_notes(base,1)
    for i in range(0,3):
        baset.add_notes(base,0.75)
        baset.add_notes(None,0.75)
        baset.add_notes(base,0.75)
        baset.add_notes(None,0.25)
        baset.add_notes(base,0.5)
        baset.add_notes(None,0.5)
        baset.add_notes(base,0.5)
        baset.add_notes(base,0.75)
        baset.add_notes(None,0.75)
        baset.add_notes(base,0.75)
        baset.add_notes(None,0.25)
        baset.add_notes(base,0.5)
        baset.add_notes(None,1)
    baset.add_notes(base, 0.75)
    baset.add_notes(None, 0.75)
    baset.add_notes(base, 0.75)
    baset.add_notes(None, 0.25)
    baset.add_notes(base, 0.5)
    baset.add_notes(None, 0.5)
    baset.add_notes(base, 0.5)
    baset.add_notes(base,1)
    baset.add_notes(base,1)
    baset.add_notes(base,0.5)
    baset.add_notes(base,0.5)
    baset.add_notes(base,1)
    baset.add_notes(None,4)

    snaret.add_notes(rimshot,1)
    snaret.add_notes(rimshot,1)
    snaret.add_notes(rimshot,1)
    snaret.add_notes(rimshot,1)
    for i in range(0,7):
        snaret.add_notes(None,1)
        snaret.add_notes(snare,1)
    snaret.add_notes(None, 1)
    snaret.add_notes(snare,0.5)
    snaret.add_notes(snare,0.25)
    snaret.add_notes(snare,0.25)
    for i in range(0,6):
        snaret.add_notes(None,1)
        snaret.add_notes(snare,1)
    snaret.add_notes(None, 2)
    snaret.add_notes(snare, 0.75)
    snaret.add_notes(snare, 0.5)
    snaret.add_notes(snare, 0.5)
    snaret.add_notes(snare, 0.25)
    for i in range(0,7):
        snaret.add_notes(None,1)
        snaret.add_notes(snare,1)
    snaret.add_notes(None, 1)
    snaret.add_notes(snare,0.5)
    snaret.add_notes(snare,0.25)
    snaret.add_notes(snare,0.25)
    for i in range(0,6):
        snaret.add_notes(None,1)
        snaret.add_notes(snare,1)
    snaret.add_notes(electricsnare, 0.5)
    snaret.add_notes(snare, 0.5)
    snaret.add_notes(None, 0.5)
    snaret.add_notes(electricsnare, 0.5)
    snaret.add_notes(None, 1)
    snaret.add_notes(electricsnare, 0.5)
    snaret.add_notes(snare,0.25)
    snaret.add_notes(snare,0.25)
    snaret.add_notes(None, 4)

    for i in range(0,4):
        tomt.add_notes(None,4)
    tomt.add_notes(None, 2)
    tomt.add_notes(hightom, 0.25)
    tomt.add_notes(hightom, 0.25)
    tomt.add_notes(None, 1)
    tomt.add_notes(midtom,0.25)
    tomt.add_notes(lowtom,0.25)
    for i in range(0,3):
        tomt.add_notes(None,4)
    tomt.add_notes([hightom,midtom],0.75)
    tomt.add_notes(None,0.75)
    tomt.add_notes([hightom,lowtom],0.75)
    tomt.add_notes(None,0.25)
    tomt.add_notes([midtom,lowtom],0.5)
    tomt.add_notes(None,1)
    for i in range(0,3):
        tomt.add_notes(None,4)
    tomt.add_notes(None, 2)
    tomt.add_notes(hightom, 0.25)
    tomt.add_notes(hightom, 0.25)
    tomt.add_notes(None, 1)
    tomt.add_notes(midtom,0.25)
    tomt.add_notes(lowtom,0.25)
    for i in range(0,3):
        tomt.add_notes(None,4)
    tomt.add_notes([hightom,midtom],0.75)
    tomt.add_notes(None,0.75)
    tomt.add_notes([hightom,lowtom],0.75)
    tomt.add_notes(None,0.75)
    tomt.add_notes([midtom,lowtom],1)
    tomt.add_notes(None,4)

    for i in range(0,5):
        cymbalt.add_notes(None,4)
    cymbalt.add_notes(cymbal, 4)
    cymbalt.add_notes(None, 4)
    cymbalt.add_notes(None, 4)
    cymbalt.add_notes(None, 3)
    cymbalt.add_notes(ridecymbal, 0.5)
    cymbalt.add_notes(ridecymbal, 0.5)
    for i in range(0,4):
        cymbalt.add_notes(None,4)
    cymbalt.add_notes(cymbal, 4)
    cymbalt.add_notes(None, 4)
    cymbalt.add_notes(None, 4)
    cymbalt.add_notes(crashcymbal, 1.5)
    cymbalt.add_notes(crashcymbal, 1.5)
    cymbalt.add_notes(crashcymbal, 1)
    cymbalt.add_notes([cymbal,crashcymbal], 4)

dopercussion(snaretrack,basetrack,highhattrack,tomtrack,cymbaltrack)










